steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    # Use Container Optimized OS
    # https://cloud.google.com/container-optimized-os/docs/
    - INSTANCE_ARGS=--image-project cos-cloud --image-family cos-stable --zone=us-east1-b --subnet=rede-gce
    - ZONE=us-east1-b
    - USERNAME=cloud-user
    # Run a script from the local build context in a Docker container
    - COMMAND=docker run -v /home/cloud-user/workspace:/workspace centos:7 bash -xe /workspace/test-scripts/no-op.sh


